### ISSUE TITLE
About CheXpert labeler

### ISSUE THREAD

**Issue by dengyi-g** [Markin-Wang/XProNet#10]
The author of R2GenCMN mentioned that CE metrics are only applicable to MIMIC-CXR because the labeling schema of CheXpert is specifically designed for MIMIC-CXR, which is different from that of IU X-RAY. 
So Will using CheXpert to label IU X-RAY directly introduce noise in practical applications?

**Comment by Markin-Wang** [comment]
Hi, I think the CheXpert is designed to label the chest-xray report rather than one specific dataset. From the [CheXpert](https://arxiv.org/pdf/1901.07031.pdf) paper, the authors generated the the label and tested the performance on the CheXpert dataset. I guess the reason why the author of R2Gen claim that is becasuse the MIMIC-CXR dataset provider prvioded the CheXpert labels and gave analysis in thier paper.

**Comment by dengyi-g** [comment]
solved
