### ISSUE TITLE
MIMIC annotation.json

### ISSUE THREAD

**Issue by Eladhi** [Markin-Wang/XProNet#8]
Hi,

Thanks for sharing your work!

I already have access to the MIMIC data, but It is arranged differently.
Could you please upload the annotations.json file for that dataset? Unfortunately, there is no access via R2Gen/CMN.

Thank you

**Comment by Markin-Wang** [comment]
Hi, thanks for your interest.
I would recommend you to apply the access for the authors of R2GenCMN.
Since the annotation file is generated and owned by the authors of R2GenCMN, I cannot send this file to you due to the possible license problem.
I am sorry that I cannot help you at this stage.

**Comment by Markin-Wang** [comment]
Hi, thanks for your interest.
I would recommend you to apply the access for the authors of R2GenCMN, they may check your approval certificate of MIMIC-CXR dataset.
Since the annotation file is generated and owned by the authors of R2GenCMN, I cannot send this file to you due to the possible license problem.
I am sorry that I cannot help you at this stage.
